---
title: "*easylca* model report report for `r params$easylca$settings$folder_name`"
date: "*created `r format(Sys.time(), '%H:%M, %B %d, %Y')`*"
output: 
  html_document:
    css: summary_report_template.css
params:
  easylca: NULL
  modeltype: NULL
  classes: NULL
---

```{r data_unpacking, echo=F}
easylca <- params$easylca 
modeltype <- params$modeltype
classes <- params$classes


model <- easylca$models[[paste0('modeltype_', modeltype)]][[classes]]
model_parameters <- extract_profile_for_plotting(model, easylca$settings)
n_indicators <- easylca$settings$use %>% length() # TODO
n_indicators_cont <- easylca$settings$use %>% length() # TODO
n_indicators_bin <- easylca$settings$categorical %>% length() # TODO
```

## Model summary

Type: `r modeltype`\
Classes: `r classes`

N = `r model$summaries$Observations`\
Number of Parameters: `r model$summaries$Parameters`

\
**Model Entropy: `r model$summaries$Entropy`**

## Model implicated class sizes

```{r class_sizes, echo=F, fig.height=classes*0.75}
class_counts <- model$class_counts$modelEstimated %>% 
  dplyr::arrange(count) %>% 
  dplyr::mutate(count = round(count), 
                greater100 = ifelse(count > 100, T, F),
                class = as.factor(sprintf('class %d', class)), 
                proportion = sprintf('%.2f %%', proportion * 100))
prop_annotation <- tail(class_counts, 3)

ggplot2::ggplot(class_counts, ggplot2::aes(x = count, 
                                           y = forcats::fct_inorder(class)))+ 
  ggplot2::geom_col(fill = 'grey') +
  ggplot2::geom_vline(xintercept = 100, color = 'black', 
                      size = 1) +
  ggplot2::annotate('text', x = 100, y = classes, label = '100', color = 'black', 
                    size = 5, hjust = -0.1) +
  ggplot2::scale_x_continuous(expand = c(0, 0.05), position = 'top') + 
  ggplot2::geom_text(data = prop_annotation, 
                     ggplot2::aes(x = count, y = forcats::fct_inorder(class),
                                  label = proportion), 
                     size = 5, color = 'white', hjust = 1.1) + 
  ggplot2::labs(x = 'model estimated count', y = '') + 
  ggplot2::theme_minimal() + 
  ggplot2::theme(axis.title = ggplot2::element_text(color = 'grey45', 
                                                    size = 12, hjust = 0), 
                 axis.text.x = ggplot2::element_text(color = 'grey45', 
                                                     size = 10, hjust = 0), 
                 axis.text.y = ggplot2::element_text(size = 14, face = 'bold'), 
                 panel.grid = ggplot2::element_blank())
```

## Indicator relevance

```{r, indicator_relevance, echo=F, fig.height=n_indicators*0.65}
plot_kruskal_profiles(model)
```

## Continuous indicators

```{r, continuous_indicators, echo=F, fig.height=ceiling(n_indicators_cont /ifelse(classes > 6, 1, 2))*2.5}
n_col_plot <- ifelse(classes > 6, 1, 2)
plot_metric_profiles(model_parameters, ncol_plot = n_col_plot)
```

## Binary indicators

```{r, binary_indicators, echo=F, fig.width=classes * 1, fig.height=n_indicators_bin *1}
plot_binary_profiles(model_parameters)
```

## Discrete indicators (upcoming)
