---
title: "*easylca* model selection report for `r params$title`"
date: "*created `r format(Sys.time(), '%H:%M, %B %d, %Y')`*"
output: 
  html_document:
    css: model_selection_report_template.css
params:
  data: NULL
  n_observations: NULL
  title: NULL
---

```{r data_unpacking, echo=F}
data <- params$data 
title <- params$title
n_observations <- params$n_observations

if(! 'T11_VLMR_PValue' %in% colnames(data)){
  data$T11_VLMR_PValue <- 'not calculated'
}
if(! 'T11_LMR_PValue' %in% colnames(data)){
  data$T11_LMR_PValue <- 'not calculated'
}
```

## Models overview

N = `r n_observations` observations

[**Local minima for BIC and saBIC** within model types are colored green. If no local minima could be found for any model type, the global lowest value is colored green.]{style="color: #1e7b1e"}

[Additionally, the **model with the most classes that has a significant VLMRT** (or adjusted VLMRT) is indicated in green for each model type.]{style="color: #1e7b1e"}

[Red indicates **models with an estimated class size below 100** for at least one class, **models that were not replicated** (2x best LL with different starting values), models with **boundary value estimates**, and **models with non-significant VLMRT (or adjusted VLMRT)**.]{style="color: #c40d20"}

```{r echo = F}
create_modeloverview_table(data)
```

## Information criteria

### BIC

```{r bic_plot, fig.height = 10, echo=F}
plot_ic_trajectory(data, 'BIC')
```

### saBIC

```{r sabic_plot, fig.height = 10, echo=F}
plot_ic_trajectory(data, 'saBIC')
```
